In [5]:
from google.colab import files
uploaded = files.upload()

Saving test.xlsx to test.xlsx


# Import and pip package

In [4]:
pip install --upgrade scikit-learn==1.3.2

In [6]:
pip install  bltk

  Using cached bltk-1.2.tar.gz (17.4 MB)
  Preparing metadata (setup.py) ... done
  Using cached sklearn-0.0.post11.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for bltk: filename=bltk-1.2-py3-none-any.whl size=17432518 sha256=27836787a2ac0a3c098e5e3288970ae13dd8703c57977ed86be12b938c841b5f
  Stored in directory: /root/.cache/pip/wheels/52/7d/57/4806e1ef5d1ad1491ce0ac43aaa0377293efbc9a81d5b7e6c8
  Created wheel for sklearn: filename=sklearn-0.0.post11-py3-none-any.whl size=2959 sha256=70ed32fc6c2e0f57f15c5bf8b3f3015089a41d8cd6a5d5737335a82c166e68e8
  Stored in directory: /root/.cache/pip/wheels/aa/9c/60/f67813603a52fc35057868f1aba0003cc75b72583dcaa2c341
Successfully built bltk sklearn


In [7]:
pip install bnlp-toolkit


In [8]:
import warnings
from sklearn.exceptions import UndefinedMetricWarning

# Ignore UndefinedMetricWarning
warnings.filterwarnings("ignore", category=UndefinedMetricWarning)


In [9]:
#bangla package import
from bltk.langtools import remove_stopwords
#from bltk.langtools import Tokenizer
import collections
import nltk
from string import punctuation
import nltk
from nltk.corpus import stopwords
from bltk.langtools.banglachars import (vowels,
                                        vowel_signs,consonants,
                                        digits,
                                        operators,
                                        punctuations,
                                        others)
print(stopwords)

<WordListCorpusReader in '.../corpora/stopwords' (not loaded yet)>


In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, roc_auc_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy import stats
import matplotlib.pyplot as plt
import sklearn.metrics as metrics

# Dataset & Insight

---



## Load dataset and insight the dataset

In [11]:
import pandas as pd
import numpy as np


df=pd.read_excel('test.xlsx')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12447 entries, 0 to 12446
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   bangla    12447 non-null  object
 1   banglish  12447 non-null  object
 2   label     12447 non-null  object
dtypes: object(3)
memory usage: 291.9+ KB


In [13]:
df.head(2)

bangla  \
0  সোনাগাছির পূজো নিয়ে বাক যুদ্ধ, তুমুল বিতর্কে জ...   
1  সেদিন বাসনওয়ালাকে যে প্যান্টটা দিয়ে বাসন কিনেছ...   

                                            banglish     label  
0  sonagachir pujo niye bak juddho, tumul bitorke...  Personal  
1  sedin basnoyalake je pjantta diye bason kinech...   Neutral

In [14]:
df.shape

(12447, 3)

In [15]:
mask = (df['label'] != 'Gender abusive')
df = df[mask]

In [16]:
df.shape

(12131, 3)

In [17]:
y=df['label']
print(df['label'].value_counts())


Personal        4225
Geopolitical    3761
Religious       1714
Political       1596
Neutral          835
Name: label, dtype: int64


In [18]:
bangla=df['bangla']

In [19]:
banglish=df['banglish']

In [20]:
label_mapping = {
    'Personal': 1,
    'Neutral': 0,
    'Religious': 3,
    'Political':4,
    'Geopolitical':2
}

# Apply the mapping to the 'label' column
y = y.map(label_mapping)


# EDA & Data Visualization & Preprocessing

---



In [21]:
from bltk.langtools import remove_stopwords
from bltk.langtools import Tokenizer

***Bangla Text Cleaning***

In [22]:
import pandas as pd
import re
import string
tokenizer = Tokenizer()
# Sample Bangla text
bangla = "আমার সাথে মাতবরি করিস না ১ ২ ৩।"

# Function to clean Bangla text
def clean_bangla_text(text):
    tokened_words = tokenizer.word_tokenizer(text)
    #print(tokened_words)
    remove_stop=remove_stopwords(tokened_words, level='hard')
    #print(remove_stop)
    #remove punctuation
    remove_punc=[word for word in remove_stop if word not in punctuations]
    #print(remove_punc)
    remove_digit=[word for word in remove_punc if word not in digits]
    #print(remove_digit)
    # Join the cleaned words
    cleaned_text = ' '.join(remove_digit)

    # Remove extra whitespaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    return cleaned_text

# Clean the Bangla text
cleaned_bangla = clean_bangla_text(bangla)

print("Process Text:",cleaned_bangla)


Process Text: সাথে মাতবরি করিস


*Banglish Text cleaning*

In [23]:
import re
import string
from nltk.tokenize import word_tokenize

# Sample Banglish text
banglish = "amar Baler hole ???????????/@kotha kos tui 123123 hobe"
def clean_banglish_text(text):
    # Remove punctuation and digits
    text = re.sub(f"[{string.punctuation}{string.digits}]", "", text)

    # Load the text file with ignored words for Banglish
    with open('banglish_stop.txt', 'r', encoding='utf-8') as file:
        ignored_words = set(word.strip() for word in file.readlines())

    # Tokenize the Banglish text
    tokens = tokenizer.word_tokenizer(text)

    # Process the tokens, excluding ignored words, and convert to lowercase
    processed_text = [token.lower() for token in tokens if token not in ignored_words]

    return ' '.join(processed_text)

# Clean the Banglish text and convert it to lowercase
cleaned_banglish = clean_banglish_text(banglish)

print("Process Text", cleaned_banglish)


Process Text baler kotha kos tui


In [24]:
set('banglish_stop.txt')

{'.', '_', 'a', 'b', 'g', 'h', 'i', 'l', 'n', 'o', 'p', 's', 't', 'x'}

## Apply the changes


In [25]:
bangla=df['bangla'].apply(clean_bangla_text)
bangla

0        সোনাগাছির পূজো বাক যুদ্ধ তুমুল বিতর্কে জড়ালেন ...
1        সেদিন বাসনওয়ালাকে প্যান্টটা দিয়ে বাসন কিনেছিলা...
2                  জুতা ছিড়ছে কেডা শালাগোরে জুতা পিডা করমু
3                        তুই কোথায় আছিস জানিনা ধর্ষণ বিচার
4             লাথি ধর্মপ্রাণ নিরীহ মানুষের লাথি গণতন্ত্রের
                               ...                        
12442    জুতা যতই দামি স্থান পায়ে স্থান কখনো মাথায় হয...
12443    দেশ ছোট ভারতের পিছিয়ে মুতার জন্যও তোদের সাথে স...
12444                   হিন্দুদের বাস্তব প্রমাণ সবাই মতামত
12445                        দেখলে শালী অস্ট্রেলিয়ান গাভী
12446    ভাই সাথে একমত নারী নেতৃত্বে থাকতে চাই ভিপি নুর...
Name: bangla, Length: 12131, dtype: object

In [26]:
banglish=df['banglish'].apply(clean_banglish_text)
banglish

0        sonagachir pujo bak juddho tumul bitorke joral...
1        sedin basnoyalake pjantta bason kinechilam onl...
2              juta chirche keda shalagore juta pida kormu
3         tui kothay achis janina shudhu dhorshon bicar na
4        lathi dhormopran nirih manusher lathi gonotontrer
                               ...                        
12442    juta joti dami sthan paj়e sthan mathaj় hoj়n...
12443    desh chot varter pichiye na mutar jonjo toder ...
12444            hinduder egulo bastob prman sobai motamot
12445                   dekhle shali ekta ostrelij়an gavi
12446    vai sathe ekomot nari netritbe thakte cai na v...
Name: banglish, Length: 12131, dtype: object

In [27]:
import pandas as pd

# Create an empty DataFrame with column names
df = pd.DataFrame(columns=['bangla', 'banglish','label'])
df['bangla']=bangla
df['banglish']=banglish
df['label']=y
df.head(3)

bangla  \
0  সোনাগাছির পূজো বাক যুদ্ধ তুমুল বিতর্কে জড়ালেন ...   
1  সেদিন বাসনওয়ালাকে প্যান্টটা দিয়ে বাসন কিনেছিলা...   
2            জুতা ছিড়ছে কেডা শালাগোরে জুতা পিডা করমু   

                                            banglish  label  
0  sonagachir pujo bak juddho tumul bitorke joral...      1  
1  sedin basnoyalake pjantta bason kinechilam onl...      0  
2        juta chirche keda shalagore juta pida kormu      1

In [28]:
df.shape

(12131, 3)

# FE [Data Handling] [Use at least 3 technique]
---


1.   TF-IDF
2.   Bag of words
3.  Count Vectorize

[Vectorization](https://www.analyticsvidhya.com/blog/2021/06/part-5-step-by-step-guide-to-master-nlp-text-vectorization-approaches/)


## TF_IDF Vectorize

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Define and fit the vectorizers for both languages on your training data
tfidf_vectorizer_bangla = TfidfVectorizer(max_features=1000, ngram_range=(1, 4))
tfidf_vectorizer_banglish = TfidfVectorizer(max_features=1000, ngram_range=(1, 4))

# Fit the vectorizers on your training data
X_bangla = tfidf_vectorizer_bangla.fit_transform(df['bangla'])
X_banglish = tfidf_vectorizer_banglish.fit_transform(df['banglish'])

# Transform the training data
X = pd.concat([pd.DataFrame(X_bangla.toarray()), pd.DataFrame(X_banglish.toarray())], axis=1).values
print(X)

y = df['label'].values
print(y)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[1 0 1 ... 1 1 4]


In [62]:
import pickle

# Save tf-idf vectorizer for Bangla
tfidf_vectorizer_bangla_filename = 'tfidf_vectorizer_bangla.sav'
with open(tfidf_vectorizer_bangla_filename, 'wb') as filehandler:
    pickle.dump(tfidf_vectorizer_bangla, filehandler)

# Save tf-idf vectorizer for Banglish
tfidf_vectorizer_banglish_filename = 'tfidf_vectorizer_banglish.sav'
with open(tfidf_vectorizer_banglish_filename, 'wb') as filehandler:
    pickle.dump(tfidf_vectorizer_banglish, filehandler)


In [53]:
# Load tf-idf vectorizer for Bangla
with open('tfidf_vectorizer_bangla.sav', 'rb') as filehandler:
    loaded_tfidf_vectorizer_bangla = pickle.load(filehandler)
print(loaded_tfidf_vectorizer_bangla)
# Load tf-idf vectorizer for Banglish
with open('tfidf_vectorizer_banglish.sav', 'rb') as filehandler:
    loaded_tfidf_vectorizer_banglish = pickle.load(filehandler)


  (0, 33)	0.60954629634437
  (0, 396)	0.6504080160507929
  (0, 437)	0.4532358384657299
  (1, 17)	0.47922796312984334
  (1, 716)	0.1513950309416593
  (1, 127)	0.2839701607801124
  (1, 16)	0.47922796312984334
  (1, 885)	0.27762598665353316
  (1, 405)	0.4714336319828658
  (1, 33)	0.3712085037706305
  (2, 301)	0.7192486325656132
  (2, 979)	0.6947527650556674
  (3, 476)	0.5735234434951064
  (3, 865)	0.5158426330888688
  (3, 468)	0.3726709212393702
  (3, 62)	0.5158426330888688
  (4, 330)	0.666418310097703
  (4, 657)	0.6570729052905574
  (4, 468)	0.352337669146442
  (5, 597)	0.53525086158944
  (5, 195)	0.5745946176337059
  (5, 893)	0.6191506606264241
  (6, 107)	0.4118511932926388
  (6, 632)	0.4435661186531555
  (6, 711)	0.6273917093661585
  :	:
  (12126, 966)	0.3866738198422085
  (12126, 682)	0.4068841142325067
  (12126, 881)	0.28867618498041026
  (12126, 259)	0.33436920292879224
  (12126, 796)	0.2460296112925585
  (12126, 107)	0.2828073514109339
  (12127, 740)	0.522418501229615
  (12127, 316

In [ ]:
import joblib

# Define the filename for the saved object
filename = 'tf-IDF_dict.joblib'

# Use joblib to save the X variable
joblib.dump(X, filename)


['tf-IDF_dict.joblib']

# Balancing Technique


1.   Under Sampling
2.   Over Sampling(smote)
3.   Tomek Links

[Balancing Technique](https://www.analyticsvidhya.com/blog/2020/07/10-techniques-to-deal-with-class-imbalance-in-machine-learning/)


## Balanced dataset using Smote

In [37]:
pip install imbalanced-learn==0.7.0


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 2.7 MB/s eta 0:00:00
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.10.1
    Uninstalling imbalanced-learn-0.10.1:
      Successfully uninstalled imbalanced-learn-0.10.1


In [39]:
from imblearn.over_sampling import SMOTE
from collections import Counter


In [40]:
print("Class distribution before SMOTE:", Counter(y))


Class distribution before SMOTE: Counter({1: 4225, 2: 3761, 3: 1714, 4: 1596, 0: 835})


In [63]:
sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X, y)


In [55]:
print("Class distribution after SMOTE:", Counter(y_resampled))


Class distribution after SMOTE: Counter({1: 4225, 0: 4225, 3: 4225, 2: 4225, 4: 4225})


In [64]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled,y_resampled, test_size=0.20, random_state=42,stratify=y_resampled)

In [57]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

16900
16900
4225
4225


In [58]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.svm import SVC

# Create an SVM model
svm_classifier = SVC()

# Fit the model on the training data
svm_classifier.fit(X_train, y_train)

# Predict y values
y_pred_svm = svm_classifier.predict(X_test)
print("Accuaracy Score:",accuracy_score(y_test,y_pred_svm))
print(classification_report(y_test, y_pred_svm))

Accuaracy Score: 0.8951479289940828
              precision    recall  f1-score   support

           0       0.82      0.94      0.88       845
           1       0.84      0.91      0.87       845
           2       0.95      0.91      0.93       845
           3       0.94      0.85      0.89       845
           4       0.95      0.88      0.91       845

    accuracy                           0.90      4225
   macro avg       0.90      0.90      0.90      4225
weighted avg       0.90      0.90      0.90      4225



In [ ]:
# save the model to disk
filename = 'svm.sav'
pickle.dump(svm_classifier, open(filename, 'wb'))

In [59]:
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest model
random_forest_classifier = RandomForestClassifier()

# Fit the model on the training data
random_forest_classifier.fit(X_train, y_train)

# Predict y values
y_pred_rf = random_forest_classifier.predict(X_test)
print("Accuaracy Score:",accuracy_score(y_test,y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Accuaracy Score: 0.9069822485207101
              precision    recall  f1-score   support

           0       0.85      0.96      0.90       845
           1       0.88      0.80      0.84       845
           2       0.94      0.92      0.93       845
           3       0.93      0.92      0.93       845
           4       0.94      0.93      0.94       845

    accuracy                           0.91      4225
   macro avg       0.91      0.91      0.91      4225
weighted avg       0.91      0.91      0.91      4225



In [66]:
import pickle

# Save the trained Random Forest model to a file
filename_rf = 'random_forest_model.sav'
with open(filename_rf, 'wb') as file:
    pickle.dump(random_forest_classifier, file)


In [ ]:
# save the model to disk
filename = 'rf.sav'
pickle.dump(random_forest_classifier, open(filename, 'wb'))

In [ ]:
import joblib

# Define the filename for the saved model
filename = 'rf.joblib'

# Use joblib to save the model
joblib.dump(random_forest_classifier, filename)


['rf.joblib']

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp_classifier = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000)
mlp_classifier.fit(X_train, y_train)
y_pred_mlp = mlp_classifier.predict(X_test)
print("Accuracy Score (MLP):", accuracy_score(y_test, y_pred_mlp))
print(classification_report(y_test, y_pred_mlp))

Accuracy Score (MLP): 0.9192899408284023
              precision    recall  f1-score   support

           0       0.89      1.00      0.94       845
           1       0.94      0.76      0.84       845
           2       0.93      0.93      0.93       845
           3       0.93      0.95      0.94       845
           4       0.92      0.97      0.94       845

    accuracy                           0.92      4225
   macro avg       0.92      0.92      0.92      4225
weighted avg       0.92      0.92      0.92      4225



label_mapping = {
    'Personal': 1,
    'Neutral': 0,
    'Religious': 3,
    'Political':4,
    'Geopolitical':2
}


In [ ]:
# Now, you can use the fitted vectorizers for transforming input data
input_bn = ["বেশি কথা কইস না"]
input_banglish = ["beshi kotha kois na "]
bangla_clean = clean_bangla_text(input_bn[0])
banglish_clean = clean_banglish_text(input_banglish[0])

# Transform the input data using the already fitted vectorizers
b1_num = tfidf_vectorizer_bangla.transform([bangla_clean]).toarray()
b2_num = tfidf_vectorizer_banglish.transform([banglish_clean]).toarray()

# Concatenate the features
X_input = pd.concat([pd.DataFrame(b1_num), pd.DataFrame(b2_num)], axis=1).values

# Now you can predict using your model (e.g., mlp_classifier)
output = random_forest_classifier.predict(X_input)
print(output)


[1]


In [ ]:
# save the model to disk
filename = 'mlp.sav'
pickle.dump(mlp_classifier, open(filename, 'wb'))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(X_train, y_train)
y_pred_dt = decision_tree_classifier.predict(X_test)
print("Accuracy Score (Decision Tree):", accuracy_score(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Accuracy Score (Decision Tree): 0.8712426035502958
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       845
           1       0.80      0.77      0.79       845
           2       0.89      0.90      0.89       845
           3       0.92      0.88      0.90       845
           4       0.92      0.89      0.90       845

    accuracy                           0.87      4225
   macro avg       0.87      0.87      0.87      4225
weighted avg       0.87      0.87      0.87      4225



In [ ]:
# save the model to disk
filename = 'dt.sav'
pickle.dump(decision_tree_classifier, open(filename, 'wb'))

# Input Check on Different Model


**label_mapping = {
    'Personal': 1,
    'Neutral': 0,
    'Religious': 3,
    'Political':4,
    'Geopolitical':2
}**

In [ ]:
# Now, you can use the fitted vectorizers for transforming input data
input_bn = ["তুই কি মাগির পুত?"]
input_banglish = ["tui ki magir put?"]
bangla_clean = clean_bangla_text(input_bn[0])
banglish_clean = clean_banglish_text(input_banglish[0])

# Transform the input data using the already fitted vectorizers
b1_num = tfidf_vectorizer_bangla.transform([bangla_clean]).toarray()
b2_num = tfidf_vectorizer_banglish.transform([banglish_clean]).toarray()

# Concatenate the features
X_input = pd.concat([pd.DataFrame(b1_num), pd.DataFrame(b2_num)], axis=1).values

# Now you can predict using your model (e.g., mlp_classifier)
output = random_forest_classifier.predict(X_input)
print(output)

if output==0:
  print("Neutral")
elif output==1:
  print("Personal")
elif output==2:
  print("GeoPolitical")
elif output==3:
  print("Religious")
else:
  print("Political")

[1]
Personal
